### ISSUE TITLE
is it Redlock?

### ISSUE THREAD

**Issue by VSilantyev** [rtckit/reactphp-redlock#3]
How could I specify multiple redis instances for redlock?

**Comment by cdosoftei** [comment]
I would instantiate a separate Custodian for each instance, but there might be better ways of doing this.

What's your use case?

**Comment by VSilantyev** [comment]
I see. I thought this repo is an implementation of redlock - distributed lock algorithm, it is mentioned on 
https://redis.io/docs/manual/patterns/distributed-locks/
It requires multiple redis instances. Seems like this is a plain, single server, redis based lock.

**Comment by cdosoftei** [comment]
Yes, you can use this library to implement the independent multi-master algorithm but yes, it's not offered out of the box. If time permits, I might consider adding the functionality in question at some point in time.
